baseURL: "https://priceandposition.com"
# Hogan has "" but that doesn't work in yml.
# CF20220117 setting up for autodeploy to Digital Ocean, following
# https://www.digitalocean.com/community/tutorials/how-to-build-and-deploy-a-hugo-site-to-digitalocean-app-platform
languageCode: en-us
title: "Price and Position"
draft: false
theme: "PaperMod"
paginate: 10

# CF20220109 added 2 lines, following https://www.banjocode.com/post/hugo/custom-css/
# custom_css = ["css/custom.css"]
# custom_js = ["js/custom.js"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Price and Position
  description: "Business and tech"
  keywords: [Blog, Portfolio, PaperMod]
  author: Craig Fisk
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  # Can be disabled by setting to false in a specific page's Front Matter.
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  # See Docs. Can set these two to true to have TOC show on pages
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Blog
    subtitle: "Business and tech"
    imageUrl: "https://assets.about.me/background/users/c/r/a/craigfisk_1640390007_976.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Craig Fisk
    buttons:
      - name: Home
        url: /
      - name: Blog
        url: posts
      - name: About
        url: about
      # - name: Categories
      #   url: categories
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    # Title: "Hi there \U0001F44B"
    Title: "Business and tech"
    Content: Welcome to the blog of Craig Fisk

  socialIcons:
    - name: "marmalade"
      url: "https://marmalade.ai"
    - name: linkedin
      url: "https://linkedin.com/in/craigfisk"
    # - name: about
    #   url: "https://about.me/craigfisk"
    - name: github
      url: "https://github.com/craigfisk"
    # - name: programming
    #   url: "https://craigfisk.com/programming"
    - name: twitter
      url: "https://twitter.com/craigfisk"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
  #    bing:
  #        SiteVerificationTag: "XYZabc"
  #    yandex:
  #        SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 5
    - identifier: posts
      name: blog
      url: /posts/
      weight: 7
    # - identifier: about
    #   name: about
    #   url: /about/
    #   weight: 8
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: craigfisk.com/programming
    #   url: https://craigfisk.com/programming
    #   weight: 30
outputs:
  home:
    - HTML
    - RSS
    - JSON
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
